name: Build Anaplane
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 8]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
      - name: Patch Anaplane
        run: |
          git config --global user.email "anaplane@2b2troll.org"
          git config --global user.name "Anaplane Build Runner"
          ./gradlew applyPatches
          ./gradlew build
          ./gradlew paperclip
          
      - uses: actions/upload-artifact@v2
        with:
          name: Anaplane-JDK${{ matrix.java }}
          path: launcher-anaplane.jar